name: Release
on:
  push:
    tags: ['v*']
jobs:
  release:
    uses: JDE-Projects/Build-Tools/.github/workflows/release.yml@41745cdc5e4ff7416d18e1b51e408ee62c93849e # Build-Tools main (installer support)
    permissions:
      id-token: write
      attestations: write
      contents: write
    with:
      app_name: SimpleSFTPAuditTool
      dist_subfolder: "Simple SFTP Audit Tool"
      python_version: "3.14"
      build_command: "Build_Simple_SFTP_Audit_Tool.bat"
      app_id: "3ABECDD8-628A-48BA-873B-83510A234269"
